
// Function to generate roadmap based on user data
import { Request, Response } from 'express';
import Roadmap from "../models/roadmap.js";

const OPENROUTER_API_KEY = process.env.GEMINI_API_KEY; // OpenRouter API key from environment variables

// OpenRouter API call function to generate the roadmap based on user data in JSON format
const callLLMForRoadmap = async (userData: any) => {
  try {
    if (!OPENROUTER_API_KEY) {
      throw new Error("GEMINI_API_KEY (OpenRouter key) is not set in environment variables");
    }

    // Construct the dynamic prompt based on user data
    const prompt = `
    Based on the provided user data, act as a professional carrer counsellor and create a 3-month roadmap to help them become a Software Development Engineer (SDE). The roadmap should include:
    - **month**: Month number (1 to 3).
    - **focus**: Main focus of the month (e.g., Frontend, Backend, Full-stack integration or any other technology specific to the user coding goals and their interets).
    - **topics**: Topics to learn each month.
    - **resources**: Recommended resources (books, websites, courses).
    - **codingChallenges**: Coding challenges to solve.
    - **project**: Project to build during the month.

    The roadmap should follow this dummy format and the tags should be in the same format as shown below the data should be changed by the user data: 
    {
      "roadmap": {
        "student": "Shashwat",
        "goal": "Full-Stack Developer (Remote)",
        "timeline": "3 Months",
        "monthlyCommitment": "1-5 hours/day",
        "months": [
          {
            "month": 1,
            "focus": "Web Fundamentals & JavaScript Basics",
            "topics": ["HTML/CSS Basics", "JavaScript Syntax", "DOM Manipulation"],
            "project": "Static Portfolio Website",
            "resources": ["freeCodeCamp Responsive Web Design", "MDN Web Docs", "JavaScript.info"],
            "codingChallenges": ["Build a calculator", "Create a responsive navbar"]
          },
          {
            "month": 2,
            "focus": "Frontend Development (React.js)",
            "topics": ["React Components", "State Management", "API Integration (Axios)"],
            "project": "E-Commerce Frontend",
            "resources": ["React Docs", "Scrimba React Course", "Frontend Masters React Path"],
            "codingChallenges": ["Build a weather app", "Create a to-do list with drag-and-drop"]
          }
        ],
        "successTips": ["Daily code practice", "Contribute to open-source", "Join dev communities"]
      }
    }

    Please generate the roadmap in this exact JSON format based on the following user data:
    User Data:
    - Name: ${userData.name}
    - Area of Interest: ${userData.areaOfInterest || 'N/A'}
    - Skill Level: ${userData.skillLevel || 'N/A'}
    - Preferred Language: ${userData.preferredLanguage || 'N/A'}
    - Experience Level: ${userData.experienceLevel || 'N/A'}
    - Learning Path: ${userData.learningPath || 'N/A'}
    - Study Year: ${userData.studyYear || 'N/A'}
    - Coding Goals: ${userData.codingGoals || 'N/A'}
    - Communication Tools: ${userData.communicationTools  || 'N/A'}
    - Assessment Type: ${userData.assessmentType || 'N/A'}
    - Career Stage: ${userData.careerStage || 'N/A'}
    - Time Commitment: ${userData.timeCommitment || 'N/A'}

    Ensure that the roadmap is realistic and personalized to the student's goals and background. 
    IMPORTANT: Return ONLY the raw JSON object, without any markdown formatting, backticks, or code blocks.
    `;

    // Make the API call via OpenRouter (OpenAI-compatible endpoint)
    const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${OPENROUTER_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.0-flash-lite-001",
        messages: [
          { role: "user", content: prompt }
        ],
      }),
    });

    if (!response.ok) {
      const errorBody = await response.text();
      console.error("OpenRouter API error:", response.status, errorBody);
      throw new Error(`OpenRouter API returned status ${response.status}`);
    }

    const data = await response.json();

    // Return the content of the roadmap generated by the LLM
    return data.choices?.[0]?.message?.content ?? null;
  } catch (error) {
    console.error("Error calling OpenRouter API:", error);
    throw new Error("Failed to fetch data from OpenRouter API");
  }
};




export const generateRoadmap = async (req: Request, res: Response) => {
    try {
      // Generate the roadmap using OpenRouter API
      let roadmapText = await callLLMForRoadmap(req.body);
      console.log("Raw LLM Response:", roadmapText);

      // Strip markdown code fences if present (```json ... ``` or ``` ... ```)
      if (roadmapText) {
        roadmapText = roadmapText.replace(/^```(?:json)?\s*\n?/i, '').replace(/\n?```\s*$/i, '').trim();
      }

      // Parse the cleaned string into a JSON object
      const parsedRoadmap = JSON.parse(roadmapText);
      console.log("Parsed Roadmap:", parsedRoadmap);

      // Return the parsed roadmap object
      return res.status(200).json({ roadmap: parsedRoadmap });
    } catch (error) {
      console.error('Error generating roadmap:', error);
      return res.status(500).json({ message: 'Error generating roadmap' });
    }
  };


// Add Roadmap function to save the generated roadmap
export const addRoadmap = async (req: Request, res: Response) => {
  try {
    // Create a new roadmap using the data from the request body
    const newRoadmap = new Roadmap({
      student: req.body.student,
      goal: req.body.goal,
      timeline: req.body.timeline,
      monthlyCommitment: req.body.monthlyCommitment,
      months: req.body.months,
      successTips: req.body.successTips,
      userId: req.body.userId,
    });

    // Save the new roadmap to the database
    await newRoadmap.save();

    // Return success response
    return res.status(200).json({ message: 'Roadmap created successfully', roadmap: newRoadmap });
  } catch (error) {
    console.error('Error adding roadmap:', error);
    return res.status(500).json({ message: 'Error adding roadmap' });
  }
};


export const fetchAllRoadmaps = async (req: Request, res: Response) => {
  try {
    // Fetch all roadmaps from the database
    const roadmaps = await Roadmap.find();

    // Return all roadmaps in the response
    return res.status(200).json(roadmaps);
  } catch (error) {
    console.error('Error fetching all roadmaps:', error);
    return res.status(500).json({ message: 'Error fetching roadmaps' });
  }
};


export const fetchRoadmapById = async (req: Request, res: Response) => {
  try {
    const { roadmapId } = req.params;

    // Fetch the roadmap by its ID
    const roadmap = await Roadmap.findById(roadmapId);

    if (!roadmap) {
      return res.status(404).json({ message: 'Roadmap not found' });
    }

    // Return the roadmap data
    return res.status(200).json(roadmap);
  } catch (error) {
    console.error('Error fetching roadmap by ID:', error);
    return res.status(500).json({ message: 'Error fetching roadmap by ID' });
  }
};


export const fetch_roadmap_by_userId = async (req: Request, res: Response) => {
  try {
    const { userId } = req.params;

    // Fetch the roadmap by userId
    const roadmap = await Roadmap.find({ userId });

    if (!roadmap) {
      return res.status(404).json({ message: 'Roadmap not found' });
    }

    // Return the roadmap data
    return res.status(200).json(roadmap);
  } catch (error) {
    console.error('Error fetching roadmap by userId:', error);
    return res.status(500).json({ message: 'Error fetching roadmap by userId' });
  }
}
